#pragma once

#define CONFIG_HAS_OP_NOP 1
#define CONFIG_HAS_OP_BREAK 1
#define CONFIG_HAS_OP_WRITE_CH 1
#define CONFIG_HAS_OP_PUSH_INT 1
#define CONFIG_HAS_OP_CH_TO_INT 1
#define CONFIG_HAS_OP_INT_TO_CH 1
#define CONFIG_HAS_CH 1
#define CONFIG_HAS_INT 1
#define CONFIG_OBERON_MATH 1